CREATE TABLE Users
(
Id INT IDENTITY(1,1) PRIMARY KEY,
Username NVARCHAR(255) NOT NULL UNIQUE,
Password TEXT NOT NULL
)

CREATE TABLE Hosts
(
Id INT IDENTITY(1,1) PRIMARY KEY,
FullName NVARCHAR(200) NOT NULL,
Email NVARCHAR(255) NOT NULL,
Phone NVARCHAR(100) NOT NULL
)

CREATE TABLE Properties
(
Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(255) NOT NULL,
Location NVARCHAR(255) NOT NULL,
PricePerNight NUMERIC(10,2) NOT NULL,
Status INT NOT NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
HostId INT NOT NULL,
CONSTRAINT IX_Property_HostId FOREIGN KEY (HostId) REFERENCES Hosts(Id) ON DELETE CASCADE,
CONSTRAINT CK_Property_Status CHECK (Status IN (0,1))
)

CREATE FULLTEXT CATALOG PropertiesCatalog;

CREATE TABLE Bookings
(
Id INT IDENTITY(1,1) PRIMARY KEY,
CheckIn DATETIME2 NOT NULL,
CheckOut DATETIME2 NOT NULL,
TotalPrice NUMERIC(10,2) NOT NULL,
PropertyId INT NOT NULL,
CONSTRAINT IX_Booking_PropertyId FOREIGN KEY (PropertyId) REFERENCES Properties(Id) ON DELETE CASCADE,
)

CREATE TABLE DomainEvents
(
Id INT IDENTITY(1,1) PRIMARY KEY,
EventType NVARCHAR(255) NOT NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
PayloadJSON TEXT NOT NULL,
PropertyId INT NOT NULL,
CONSTRAINT IX_DomainEvent_PropertyId FOREIGN KEY (PropertyId) REFERENCES Properties(Id) ON DELETE CASCADE,
)

